### ISSUE TITLE
HCA Atlas Tracker - Go Live Steps

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#1]
```[tasklist]
### Project Inception
- [ ] Business Requirements Document
- [ ] https://github.com/clevercanary/hca-atlas-tracker/issues/10
- [ ] Technical System Design
- [ ] Project Plan / PM
```

```[tasklist]
### Dev Setup
- [ ] https://github.com/clevercanary/hca-atlas-tracker/issues/2
- [ ] https://github.com/clevercanary/hca-atlas-tracker/issues/3
- [ ] Atlas Tracker CC Dev environment setup
- [ ] Authentication
- [ ] Authorization
- [ ] Manage atlases
- [ ] Manage component atlases
- [ ] Manage source datasets
- [ ] Auto detect Data Explorer atlas/dataset link
- [ ] Auto detect CELLxGENE collection link
- [ ] Auto detect CAP link
```
