### ISSUE TITLE
Initial repo setup

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#2]
Setup the repository with the usual items such as:

```[tasklist]
### Tasks
- [ ] Jest
- [ ] Playwright
- [ ] ES Lint
- [ ] TS Config
- [ ] Commitlint
- [ ] LIcense (Dave)
- [ ] Branch Protection Rules
- [ ] GH Action to run tests,  test lint and compile
- [ ] Add other items to get to parity with DataBiosphere/data-browser
- [ ] What else?
- [ ] Setup Readme
```

**Comment by NoopDog** [comment]
Complete
