### ISSUE TITLE
Allow the Atlas page to be used as an atlas roadmap/plan

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/hca-atlas-tracker#229]
### Need
Admins must communicate target dates for atlases to help prioritize work and allocate resources.

```[tasklist]
### Tasks
- [ ] Add target completion to the atlas model and edit API
- [ ] Add target completion to the atlas view and edit forms and table 
- [ ] Add a targetCompletion patch API for the batch update of atlas target completion dates
- [ ] Add targetCompleteion batch update API on Atlas list
```
